import { AppState } from "./index";

export const mockState: AppState = {
    metadataState: {
        appInstallDate: "2023-09-01",
        isFirstTimeRendered: false,
    },
    settingsState: {
        stopwatchSettings: { startOnDoneSet: false },
        keepAwake: true,
        theme: "dark",
        language: "de",
        unitSystem: "metric",
        switchToNextExercise: false,
        searchManual: "",
        updatePrefilledWorkoutValues: true,
    },
    measurementState: {
        sorting: "A_Z",
        measurements: [
            {
                measurementId: "measurement-1",
                name: "Körpergewicht",
                type: "weight",
                data: [
                    { isoDate: "2023-12-01", value: "70" },
                    { isoDate: "2023-12-02", value: "70" },
                    { isoDate: "2023-12-03", value: "70" },
                    { isoDate: "2023-12-04", value: "72" },
                    { isoDate: "2023-12-05", value: "73" },
                    { isoDate: "2023-12-06", value: "75" },
                    { isoDate: "2023-12-07", value: "74" },
                    { isoDate: "2023-12-08", value: "74" },
                    { isoDate: "2023-12-09", value: "74" },
                    { isoDate: "2023-12-10", value: "74" },
                    { isoDate: "2023-12-11", value: "74" },
                    { isoDate: "2023-12-12", value: "74" },
                    { isoDate: "2023-12-13", value: "74" },
                    { isoDate: "2023-12-14", value: "74" },
                    { isoDate: "2023-12-15", value: "74" },
                ],
                higherIsBetter: true,
            },
            {
                measurementId: "measurement-2",
                name: "Körperfettanteil",
                type: "percent",
                data: [
                    { isoDate: "2023-12-01", value: "15" },
                    { isoDate: "2023-12-02", value: "15" },
                    { isoDate: "2023-12-03", value: "15" },
                    { isoDate: "2023-12-04", value: "16" },
                    { isoDate: "2023-12-05", value: "14" },
                    { isoDate: "2023-12-06", value: "13" },
                    { isoDate: "2023-12-07", value: "12" },
                ],
            },
        ],
    },
    workoutState: {
        templateSorting: "A_Z",
        workoutSorting: "A_Z",
        workouts: [
            {
                workoutId: "workout-1",
                name: "Push Workout 1",
                exercises: [
                    {
                        exerciseId: "exercise-1",
                        name: "Bankdrücken",
                        sets: "5",
                        reps: "5",
                        weight: "65",
                        type: "WEIGHT_BASED",
                        pauseSeconds: "0",
                        pauseMinutes: "2",
                        durationSeconds: "",
                        durationMinutes: "",
                    },
                    {
                        exerciseId: "exercise-2",
                        name: "Überkopfdrücken",
                        sets: "5",
                        reps: "5",
                        weight: "10",
                        type: "WEIGHT_BASED",
                        pauseSeconds: "0",
                        pauseMinutes: "2",
                        durationSeconds: "",
                        durationMinutes: "",
                    },
                    {
                        exerciseId: "exercise-3",
                        name: "Butterfly",
                        sets: "5",
                        reps: "5",
                        weight: "10",
                        type: "WEIGHT_BASED",
                        pauseSeconds: "0",
                        pauseMinutes: "2",
                        durationSeconds: "",
                        durationMinutes: "",
                    },
                    {
                        exerciseId: "exercise-4",
                        name: "Seitheben",
                        sets: "5",
                        reps: "5",
                        weight: "10",
                        type: "WEIGHT_BASED",
                        pauseSeconds: "0",
                        pauseMinutes: "2",
                        durationSeconds: "",
                        durationMinutes: "",
                    },
                    {
                        exerciseId: "exercise-5",
                        name: "Trizeps",
                        sets: "5",
                        reps: "5",
                        weight: "10",
                        type: "WEIGHT_BASED",
                        pauseSeconds: "0",
                        pauseMinutes: "2",
                        durationSeconds: "",
                        durationMinutes: "",
                    },
                ],
                doneWorkouts: [
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-01",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "65",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "65",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "65",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "65",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-27",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "67",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "67",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "67",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "67",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "12",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-29",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "70",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "70",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "70",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "70",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "6",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "10",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-02",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "72.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "72.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "72.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "72.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-04",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "75",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "75",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "75",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "75",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "6",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "15",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-05",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "77.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "77.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "77.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "77.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-08",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "80",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "80",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "80",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "80",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "6",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "17.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-11",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "82.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "82.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "82.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "82.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "20",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "20",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "20",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "20",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-01-13",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-01",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "85",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-01",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-151",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-122",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "22.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-15",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-01",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-152",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "6",
                                        weight: "87.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-222",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "12",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "25",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "25",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "25",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-16",
                        originalWorkoutId: "workout-1",
                        isoDate: "2023-12-01",
                        duration: (57 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-153",
                                name: "Benchpress",
                                note: "Felt really good today",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "90",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "90",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "90",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "90",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-224",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "250000",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "250000",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "250000",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "250000000000",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                    {
                        doneWorkoutId: "workout-124",
                        originalWorkoutId: "workout-1",
                        isoDate: "2024-03-01",
                        duration: (50 * 60 * 1000).toString(),
                        doneExercises: [
                            {
                                doneExerciseId: "exercise-137",
                                name: "Benchpress",
                                note: "Maybe bit slower on the end",
                                fallbackSets: [],
                                originalExerciseId: "exercise-1",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "95",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "95",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "4",
                                        weight: "95",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "4",
                                        weight: "95",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                            {
                                doneExerciseId: "exercise-14",
                                name: "Military Press",
                                fallbackSets: [],
                                originalExerciseId: "exercise-2",
                                sets: [
                                    {
                                        reps: "5",
                                        weight: "12.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                    {
                                        reps: "5",
                                        weight: "12.5",
                                        durationMinutes: "",
                                        durationSeconds: "",
                                        confirmed: true,
                                    },
                                ],
                                type: "WEIGHT_BASED",
                            },
                        ],
                    },
                ],
            },
        ],
    },
    errorState: {
        errors: [],
    },
    purchaseState: {
        pro: false,
        availablePackages: [],
        loaded: false,
    },
};

export const emptyState = {
    workoutState: {
        templateSorting: "MOST_RECENT",
        workoutSorting: "LONGEST_AGO",
        workouts: [],
    },
    measurementState: {
        sorting: "A_Z",
        measurements: [],
    },
    metadataState: {
        appInstallDate: "2023-11-11",
        isFirstTimeRendered: true,
    },
    errorState: {
        errors: [],
    },
    purchaseState: {
        pro: false,
        availablePackages: [],
        loaded: false,
    },
    settingsState: {
        stopwatchSettings: { startOnDoneSet: true },
        keepAwake: true,
        language: "de",
        theme: "system",
        unitSystem: "metric",
        switchToNextExercise: false,
        searchManual: "",
        updatePrefilledWorkoutValues: true,
    },
} satisfies AppState;
